# Railway deployment configuration
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run preview"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NIXPACKS_BUILD_CMD = "npm run build"
NIXPACKS_START_CMD = "npm run preview"
NODE_VERSION = "18"
